version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - app/.env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

volumes:
  sql: